"""initial user token metrics and blacklist schemas

Revision ID: 95f02734ece2
Revises: 
Create Date: 2026-05-14 12:50:11.728492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95f02734ece2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token_blacklist',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_token_blacklist_expires_at'), 'refresh_token_blacklist', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('app_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_tokens_user_id'), 'app_tokens', ['user_id'], unique=False)
    op.create_table('metric_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_token_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_token_id'], ['app_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_events_app_token_id'), 'metric_events', ['app_token_id'], unique=False)
    op.create_index(op.f('ix_metric_events_device_id'), 'metric_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_metric_events_event_type'), 'metric_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_metric_events_session_id'), 'metric_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_metric_events_timestamp'), 'metric_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_events_timestamp'), table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_session_id'), table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_event_type'), table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_device_id'), table_name='metric_events')
    op.drop_index(op.f('ix_metric_events_app_token_id'), table_name='metric_events')
    op.drop_table('metric_events')
    op.drop_index(op.f('ix_app_tokens_user_id'), table_name='app_tokens')
    op.drop_table('app_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_token_blacklist_expires_at'), table_name='refresh_token_blacklist')
    op.drop_table('refresh_token_blacklist')
    # ### end Alembic commands ###
